.github/workflows/on_pull_request.yml, package.json, pnpm-lock.yaml
Since a couple of commits ago, our pipelines for PRs were not running properly. It seems to have to do with the `nrwl/nx-set-shas@v4` not working properly.
=> fix: PRs CI not working due to NX SHA action

.github/workflows/on_pull_request.yml, libs/zephyr-agent/src/lib/logging/ze-log-event.ts, libs/zephyr-agent/src/zephyr-engine/index.ts, libs/zephyr-agent/src/zephyr-engine/resolve_remote_dependency.ts, libs/zephyr-edge-contract/src/lib/ze-api/converted-graph.ts, libs/zephyr-repack-plugin/src/lib/with-zephyr.ts, libs/zephyr-repack-plugin/src/lib/ze-repack-plugin.ts, libs/zephyr-xpack-internal/jest.config.ts, libs/zephyr-xpack-internal/src/federation-dashboard-legacy/get-build-stats.ts, libs/zephyr-xpack-internal/src/federation-dashboard-legacy/utils/convert-to-graph/convert-to-graph.ts, libs/zephyr-xpack-internal/src/xpack-extract/ze-xpack-upload-agent.ts, nx.json, package.json, pnpm-lock.yaml
- resolving correct build target for ios and android 
- allow skipping file upload if it's a host application
- additional logging if skipping file upload 
- stop resolving remote url if it's a custom environment
- Failed to resolve correct dependency on new canary version, [internal conversation](https://zephyr-cloud.slack.com/archives/C07LWPWAF4J/p1737640155597869)
Tested with @Nsttt 
WIP
=> feat: repack build_target

libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> fix: bump versions to v0.0.32

README.md, libs/vite-plugin-zephyr/README.md, libs/zephyr-agent/README.md, libs/zephyr-edge-contract/README.md, libs/zephyr-repack-plugin/README.md, libs/zephyr-rspack-plugin/README.md, libs/zephyr-webpack-plugin/README.md, libs/zephyr-xpack-internal/README.md
- Update readme
N/A
N/A
- Finish readme for other plugins
=> feat: update readme 

.github/workflows/on_canary_release.yml
Add a summary to canary release to visualize the published canary version.
=> fix: add canary action summary

package.json, pnpm-lock.yaml
Fixes for;
- https://github.com/ZephyrCloudIO/zephyr-packages/security/dependabot/27
- https://github.com/ZephyrCloudIO/zephyr-packages/security/dependabot/26
=> deps: upgrade vitest related libs

libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> deps: bump packages to 0.0.34

libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> deps: bump packages to 0.0.35

.gitignore, examples/parcel-react/.parcelrc, examples/parcel-react/index.html, examples/parcel-react/package.json, examples/parcel-react/src/App.tsx, examples/parcel-react/src/index.tsx, examples/parcel-react/tsconfig.json, examples/testing-matrix.sh, libs/parcel-reporter-zephyr/.eslintrc.json, libs/parcel-reporter-zephyr/.npmignore, libs/parcel-reporter-zephyr/LICENSE, libs/parcel-reporter-zephyr/README.md, libs/parcel-reporter-zephyr/jest.config.ts, libs/parcel-reporter-zephyr/package.json, libs/parcel-reporter-zephyr/project.json, libs/parcel-reporter-zephyr/src/index.ts, libs/parcel-reporter-zephyr/src/lib/get-assets-map.ts, libs/parcel-reporter-zephyr/src/lib/on-build-start.ts, libs/parcel-reporter-zephyr/src/lib/on-build-success.ts, libs/parcel-reporter-zephyr/tsconfig.json, libs/parcel-reporter-zephyr/tsconfig.lib.json, libs/parcel-reporter-zephyr/tsconfig.spec.json, libs/zephyr-agent/src/index.ts, libs/zephyr-agent/src/zephyr-engine/index.ts, libs/zephyr-rspack-plugin/repomix-output.txt, pnpm-lock.yaml
This PR adds support for Parcel to be deployed into Zephyr.
https://nestor-lopez-613-zephyr-packages-zephyr-packages--973024229-ze.zephyr-cloud.io/
Canary: https://www.npmjs.com/package/parcel-reporter-zephyr/v/0.0.0-canary-20250227203709
1. Go into the Parcel plugin and build it.
2. Go into the parcel example and try to build and see if it deploys to Zephyr.
https://github.com/ZephyrCloudIO/zephyr-documentation/pull/84
- [] I have written new tests (if applicable)
=> feat: add parcel plugin support

libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> chore: bump packages to v0.0.37

libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
Version bump to 0.0.3
N/A 
Urgent fix for latest version of Repack 
N/A 
N/A
=> feat: version 0.0.38

libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> fix: bump packages 0.0.39

package.json
Generate provenance statements when publishing to npm.
https://docs.npmjs.com/generating-provenance-statements
This is an example of how it will show on npm:
=> feat: use npm provenance when publishing packages 

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json
=> tag: v0.0.40

.github/workflows/on_release.yml
Undo changes to release workflow
=> fix: undo changes to release workflow

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json
=> tag: v0.0.42

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, tsconfig.base.json
=> feat: add required package.json fields to publish with provenance

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> release: bump to version 43

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> chore: bump versions to v0.0.44

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> chore: bump version 0.0.46

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> chore: bump plugins to v47

README.md, docs/CONTRIBUTING.md, package.json
Add a new contributing guide for contributors 
N/A
Discussed with @Thegrep01  
N/A
N/A
=> feat: contributing guide

libs/zephyr-agent/src/lib/http/http-request.ts
add `api_host` to have ability build app for preview environment
N/A
build app in preview
N/A
=> fix: build for preview environment

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> feat: version bump v0.0.48

libs/rollup-plugin-zephyr/README.md, libs/vite-plugin-zephyr/README.md, libs/vite-plugin-zephyr/src/lib/vite-plugin-zephyr.ts, libs/zephyr-modernjs-plugin/README.md, libs/zephyr-repack-plugin/README.md, libs/zephyr-rolldown-plugin/README.md, libs/zephyr-rspack-plugin/README.md, libs/zephyr-webpack-plugin/README.md
Add `Get staretd` command in readme for plugins that has example applications available
N/A 
https://github.com/ZephyrCloudIO/zephyr-packages/pull/140
N/A 
N/A
=> feat: add get started command 

libs/vite-plugin-zephyr/src/lib/internal/extract/__test__/extract_vite_assets_map.test.ts, libs/vite-plugin-zephyr/src/lib/internal/extract/extract_vite_assets_map.ts
Fixing an issue involving the upload of images.
Example repository https://github.com/nrwl/partners-roundtable
Internal
Build from the example repository using changes on this branch must correctly display the image.
Test other vite examples to measure impact.
=> fix: parse as buffer instead of text decode

libs/zephyr-agent/src/lib/logging/ze-log-event.ts
Keep global level logs as is in DEBUG mode.
=> fix: keep global logs out of debug logs

examples/react-micro-frontends/apps/team-red/package.json, examples/rspack-mf/apps/host/package.json, examples/rspack-nx-mf/apps/host/package.json, examples/vite-react-mf/host/package.json, libs/zephyr-agent/src/lib/build-context/__test__/ze-util-parse-ze-dependencies.test.ts, libs/zephyr-agent/src/lib/build-context/ze-util-parse-ze-dependencies.ts
Fixing module federated examples with new dependency resolution workflow.
Build the federated applications and check their remote resolutions.
=> fix: adjusting remote resolution on samples

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> chore: bump version to 0.0.51

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> chore: bump version to 0.0.52

libs/create-zephyr-apps/package.json, libs/parcel-reporter-zephyr/package.json, libs/rollup-plugin-zephyr/package.json, libs/vite-plugin-zephyr/package.json, libs/zephyr-agent/package.json, libs/zephyr-edge-contract/package.json, libs/zephyr-modernjs-plugin/package.json, libs/zephyr-repack-plugin/package.json, libs/zephyr-rolldown-plugin/package.json, libs/zephyr-rspack-plugin/package.json, libs/zephyr-rspress-plugin/package.json, libs/zephyr-webpack-plugin/package.json, libs/zephyr-xpack-internal/package.json, package.json
=> chore: bump version to 0.0.54

libs/zephyr-rolldown-plugin/README.md, libs/zephyr-rspack-plugin/README.md, libs/zephyr-rspress-plugin/README.md, libs/zephyr-webpack-plugin/README.md
Removing options from withZephyr from the docs because we still don't have any.
=> chore: remove withZephyr options from docs

libs/create-zephyr-apps/README.md, libs/create-zephyr-apps/src/templates.ts
Add airbnb clone example to `create-zephyr-apps` 
N/A 
N/A
`pnpm --filter create-zephyr-apps run dev` and select airbnb clone example to create example application and run 
within the example, run 
```
pnpm install 
pnpm build-remotes 
pnpm build-host
```
N/A
=> feat: add airbnb clone to `create-zephyr-apps` 

package.json, pnpm-lock.yaml
=> chore: fix webpack version mismatch

README.md
=> feat: add repobeats

libs/zephyr-edge-contract/src/lib/snapshot.ts
Version URL and publishing timestamp to the Snapshot type
=> feat: add version url and publish timestamp to snapshot
